### ISSUE TITLE
Is it intended/desired to have the RPC connection using the HTTP_PROXY environment variable?

### ISSUE THREAD

**Issue by 21M4TW** [OCEAN-xyz/datum_gateway#30]
Hi,

while trying datum, I have noticed that curl in json_rpc_call was attempting to use the proxy defined in my HTTP_PROXY environment variable to connect to the RPC. Was it intended? It does not seem to be how my other bitcoin services behave when connecting to the RPC when HTTP_PROXY is set. Maybe you should consider using the CURLOPT_NOPROXY option if it was not desired...

**Comment by luke-jr** [comment]
Seems like that's the purpose of `HTTP_PROXY`? The DATUM protocol isn't HTTP, so the var has no other purpose...

https://everything.curl.dev/usingcurl/proxies/env.html
