### ISSUE TITLE
Do you plan to release DATUM Prime?

### ISSUE THREAD

**Issue by GregTonoski** [OCEAN-xyz/datum_gateway#8]
Also, is there any other way to test DATUM protocol beside connecting to datum-beta1.mine.ocean.xyz?

**Comment by luke-jr** [comment]
Eventually, but this git repo is for issues in the Gateway specifically. We have GitHub Discussions  enabled, which may be a better place, and OCEAN also has a Discord community (which will shortly have DATUM-specific channels).
